[server.aj]
tmpl = "192.168.1.3 hjb/hello group=aliyun"
note = "aliyun jumper"
[server.gwc]
tmpl = "192.168.(29.11 37.82) ft/na id=(11 82) proxy=aj group=aliyun"
note = "api-gateway"
[server.gwa]
tmpl = "192.168.8.(22-26):22 ft/na id=(22-26) proxy=aj group=aliyun"
note = "API网关测试"
