# Make sure to check the documentation at https://goreleaser.com, https://goreleaser.com/customization/
project_name: logtail
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
builds:
  -
    main: ./cmd/bssh/main.go
    hooks:
      post: ./upx.sh
    goos:
      - darwin
env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
