version: 2.1

jobs:
  build-go-latest:
    docker:
      - image: golang:latest
    working_directory: /go/src/github.com/blacknon/lssh
    steps:
      - checkout
      - run: make
      - run: make install
      - run: lssh --help
      - run: lscp --help

workflows:
  version: 2
  build:
    jobs:
      - build-go-latest
