# hostInfoEnabled = 0
# hostInfoScriptFile = "hostinfo.sh"

hosts = [
    "user:pass@192.168.1.1:8022 note=host8022 id=host1 group=xxx",
]

web_port = 0 # auto create a listening port for dash or system status page, -1 to disable it.

[log]
enable = true
timestamp = true
dirpath = "~/.bssh.log"

[extra]
Passphrase = "6425B5BD-4C88-4C5D-AF75-E22E357821BC"
Grouping = 0
AutoEncryptPwd = 0

[server.example1]
addr = "192.168.100.101"
port = "22"
user = "test"
pass = "Password"
note = "Password Auth Server"

#
[server.example2]
addr = "192.168.100.102"
port = "22"
user = "test"
key = "/tmp/key.pem"
note = "Key Auth Server"

[server.demo1]
tmpl = "192.168.1.2:8022 root/123456"
note = "demo1"

[server.demo2]
tmpl = "192.168.1.4 root/xxxx note=demo2"

[server.demo3]
tmpl = "192.168.1.(21-23 30 33):8022 app/xxx id=(21-23 30 33) group=demo3"

[server.demoJumper]
tmpl = "192.168.2.3:22 aaa/11111"

[server.demo4]
tmpl = "192.168.2.(7 12) app/na proxy=demoJumper"

[server.demo5]
tmpl = "192.168.2.3:22 aaa/11111"
initial_cmd = "{CtrlG}信云信书{2N}{CtrlR}10.66.55.44{2N}{CtrlA}oper{3N}"

# this config will be expanded to six items by the template tmpl
[server.demo6]
tmpl = "192.168.1.129:5107 huihui/xxxx IP=10.6.3.(1-6) id=(1-6)"
# {IP} will substituted first by properties defined in the tmpl above
# {CtrlG} means Ctrl+G, similar with {CtrlA}, {CtrlR} and etc.
# {N} mean enter, {2N} means two enters
initial_cmd = "{CtrlG}api-gw{2N}{CtrlR}{IP}{2N}{CtrlA}msspoper{4N}"
note = "demo6_{IP}"

# use {Prompt} to prompt a password from terminal input and then saved back in {PBE}XXX format.
[server.demo7]
tmpl = "12.26.18.62:21063 root/{Prompt} group=qqyun"
note = "192.1.1.14"
